# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

environment:
  SHELL: "windows"

  matrix:

  - PYTHON: "C:\\Python35"
    PYTHON_VERSION: "3.5.x"
    PYTHON_ARCH: "64"

  - PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.x"
    PYTHON_ARCH: "64"

platform:
- x64

install:
- "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
- "set PYTHONIOENCODING=utf-8"
- "python --version"
- "python -c \"import struct; print(struct.calcsize('P') * 8)\""
- "pip install --upgrade pip wheel pipenv"
- "pipenv install --dev"

build: off

test_script:
- "pipenv run pytest"

# enable one day when pipenv works
# after_test:
# - "codecov"
